// Types to mirror your C# entity in a UI-friendly way
export type NoteCard = {
  id: string;
  title: string;
  excerpt: string; // derived from Content, first lines etc.
  status: "Draft" | "Published" | "Archived";
  tags: string[];
  updatedAt: Date | string;
  content: string; // long description / full text
};

export const notes: NoteCard[] = [
  {
    id: "n-001",
    title: "JavaScript Scope & Closures",
    excerpt: "Notes on lexical scope, closure patterns, and common pitfalls…",
    status: "Published",
    tags: ["JS", "Basics"],
    updatedAt: "2025-08-30",
    content: [
      "Lexical scope is determined at write-time, not run-time. Each function creates a new scope with its own variable environment that closes over identifiers from outer scopes. The “scope chain” is formed by nested functions, and closures are simply functions that remember references to variables from their defining environment.",
      "",
      "Key points:",
      "- `var` is function-scoped; `let`/`const` are block-scoped. Prefer `const` by default.",
      "- Closures enable encapsulation (module pattern), memoization, and function factories.",
      "- Common pitfalls: capturing the same loop variable (use `let`), late-binding in callbacks, and accidental globals when omitting `const/let`.",
      "- IIFE (Immediately Invoked Function Expression) was historically used to create local scope; modules serve this role today.",
      "- Be mindful of memory: long-lived closures can keep large objects alive.",
      "",
      "Example:",
      "function makeCounter(start = 0) {",
      "  let n = start;",
      "  return () => ++n; // closes over n",
      "}",
      "const next = makeCounter(10); // 11, 12, 13…",
    ].join("\n"),
  },
  {
    id: "n-002",
    title: "React Rendering & Keys",
    excerpt:
      "Why keys matter, reconciliation, and list rendering best practices…",
    status: "Draft",
    tags: ["React", "UI"],
    updatedAt: "2025-08-28",
    content: [
      "React's reconciliation algorithm uses keys to match elements between renders. A stable, unique key preserves component identity, state, and DOM nodes across updates.",
      "",
      "Guidelines:",
      "- Use stable IDs from your data as keys; avoid array indices except for static lists.",
      "- Changing keys forces remounts, which resets component state—useful intentionally (e.g., reset a form).",
      "- Keys belong on the direct children in a list, not inside the child component.",
      "- Rendering performance: reduce unnecessary re-renders with memoization (`React.memo`, `useMemo`, `useCallback`) when profiling indicates a bottleneck.",
      "- Beware of key collisions; they lead to subtle bugs (incorrect state mapping).",
      "",
      "When items are inserted/removed, correct keys ensure minimal DOM changes and proper state retention.",
    ].join("\n"),
  },
  {
    id: "n-003",
    title: "Node.js Streams",
    excerpt: "Readable, Writable, Duplex, and Transform streams with examples…",
    status: "Published",
    tags: ["Node", "Backend"],
    updatedAt: "2025-08-25",
    content: [
      "Streams provide incremental, backpressure-aware I/O. Types:",
      "- Readable: source of data (e.g., fs.createReadStream)",
      "- Writable: sink of data (e.g., fs.createWriteStream)",
      "- Duplex: both readable and writable (e.g., net.Socket)",
      "- Transform: Duplex that modifies data (e.g., zlib, crypto)",
      "",
      "Best practices:",
      "- Use `stream.pipeline` to compose streams with proper error propagation.",
      "- Respect backpressure; `write()` returns false → wait for 'drain'.",
      "- `objectMode` handles non-Buffer objects; adjust `highWaterMark` for throughput.",
      "- Prefer async iteration: `for await (const chunk of readable) { ... }`.",
      "",
      "Example pipeline:",
      "import { createReadStream, createWriteStream } from 'fs';",
      "import { createGzip } from 'zlib';",
      "import { pipeline } from 'stream/promises';",
      "await pipeline(",
      "  createReadStream('input.log'),",
      "  createGzip(),",
      "  createWriteStream('input.log.gz')",
      ");",
    ].join("\n"),
  },
  {
    id: "n-004",
    title: "MongoDB Indexing Cheatsheet",
    excerpt: "Compound indexes, partial indexes, explain plans, and pitfalls…",
    status: "Published",
    tags: ["MongoDB", "DB"],
    updatedAt: "2025-08-22",
    content: [
      "Indexing fundamentals:",
      "- Single vs compound: compound obeys the prefix rule; order matters for sort and equality/range efficiency.",
      "- Covered queries: all fields (filter/projection) come from the index → no collection scan.",
      "- Partial index: only indexes docs matching a filter, reducing size and write cost.",
      "- Sparse index: skips documents missing the field; careful with null semantics.",
      "- TTL index: auto-expires documents after a duration; great for logs/sessions.",
      "- Unique index: enforces uniqueness at the database level.",
      "",
      "Performance tips:",
      "- Analyze `explain()` to inspect winning plan, stage (IXSCAN/COLLSCAN), and index bounds.",
      "- Avoid over-indexing; each index slows writes and consumes RAM.",
      "- Align sort with index order; consider `hint()` only for debugging or rare cases.",
      "",
      "Pattern: For queries `{ a: eq, b: range }` use `{ a: 1, b: 1 }`. If sorting by `b`, include sort direction in the index.",
    ].join("\n"),
  },
  {
    id: "n-005",
    title: "HTTP Caching Deep Dive",
    excerpt: "Cache-Control, ETag, Last-Modified, and real-world patterns…",
    status: "Draft",
    tags: ["HTTP", "Perf"],
    updatedAt: "2025-08-18",
    content: [
      "HTTP caching reduces latency and server load with freshness and validation.",
      "- Freshness: `Cache-Control: max-age`, `s-maxage` (for shared caches/CDNs), `public/private`, `immutable`, `stale-while-revalidate`, `stale-if-error`.",
      "- Validation: ETag/If-None-Match and Last-Modified/If-Modified-Since enable 304 Not Modified.",
      "- `Vary` controls cache key dimensions (e.g., `Vary: Accept-Encoding, Accept-Language`).",
      "- For APIs, prefer strong validators (ETag) to avoid recomputing heavy responses.",
      "- Use versioned asset URLs (hash in file name) + long max-age for static files.",
      "",
      "Patterns:",
      "- Static assets: `Cache-Control: public, max-age=31536000, immutable` with hashed filenames.",
      "- HTML/documents: short `max-age` with revalidation via ETag.",
      "- CDN: leverage `s-maxage`, `stale-while-revalidate` to smooth origin spikes.",
    ].join("\n"),
  },
  {
    id: "n-006",
    title: "TypeScript Utility Types",
    excerpt: "Pick, Omit, Partial, Record, ReturnType, and custom utilities…",
    status: "Published",
    tags: ["TS", "Types"],
    updatedAt: "2025-08-15",
    content: [
      "Built-ins:",
      "- `Partial<T>`/`Required<T>`: toggle optionality.",
      "- `Readonly<T>`: lock properties; pair with `as const`.",
      "- `Pick<T, K>`/`Omit<T, K>`: select or exclude fields.",
      "- `Record<K, T>`: map-like object with constrained keys.",
      "- `ReturnType<F>`/`Parameters<F>`/`ConstructorParameters<C>`/`InstanceType<C>`.",
      "- `Extract<A, B>`/`Exclude<A, B>`: set operations on unions.",
      "- `NonNullable<T>`: remove `null | undefined`.",
      "- `Awaited<T>`: unwrap Promise and nested thenables.",
      "",
      "Patterns:",
      "- Mapped types + key remapping (`as`) for renaming properties.",
      "- Template literal types for string patterns (e.g., IDs like `user_${string}`).",
      "- Discriminated unions for exhaustive switch safety.",
      "- Utility composition: `Readonly<Pick<T, 'id' | 'createdAt'>>`.",
      "",
      "Keep domain types minimal and derive view models with utilities to avoid duplication.",
    ].join("\n"),
  },
];
